#!/bin/bash
### BEGIN INIT INFO
# Provides:          loginvsid
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: loginvsid
# Description:       loginvsid
### END INIT INFO

start() {
  cd /loginvsi
  docker run -d -p 9000:9000 -v /loginvsi:/loginvsi -v /certificates:/certs -v /var/run/docker.sock:/var/run/docker.sock -v /opt/portainer:/data --name portainer portainer/portainer --ssl --sslkey /certs/portainer.key --sslcert /certs/portainer.crt --admin-password '{{ADMIN_PASS}}' --logo /loginvsi/logo.png -H unix:///var/run/docker.sock
  docker run -d -p 80:80 -v /var/run/webmin:/var/run/container-control --name webmin tragus/webmin
  export $(cat .env); docker stack deploy --compose-file ./docker-compose.yml VSI &>/dev/null
  sleep 5 &>/dev/null
  TOTAL=$(docker stack services VSI --format "{{.Replicas}}" | wc -l)
  MAXCOUNT=300
  COUNT=0
  while [ $COUNT -le $MAXCOUNT ];
  do    
    COUNT=$((COUNT+1))
    RUNNING=$(docker stack services VSI --format "{{.Replicas}}" | grep "1/1" | wc -l)
    if [ $TOTAL -eq $RUNNING ]; then
      printf "Starting LoginVSI services: \e[32m[DONE]\e[39m \r\n" 
      DONE="true" 
      break
    else
      printf "Starting LoginVSI services: \e[36m[%s]\e[39m:\r\n" "$TOTAL/$RUNNING"
    fi
    sleep 1 &>/dev/null  
  done
  if [ -z $DONE ]; then
    echo "Starting services timedout after $MAXCOUNT seconds"
  fi
}

stop() { 
  printf "Stopping LoginVSI services \r\n"
  docker stop $(docker ps -qf name=VSI_) &>/dev/null    
  printf "Stopping LoginVSI services: \e[32m[DONE]\e[39m \r\n"
}

restart() {
  stop
  start
}

update() {
  cd /loginvsi
  wget #URL to download latest yml from
  docker rmi $(docker image ls loginvsi/* -q)
  export $(cat .env); docker stack deploy --compose-file ./docker-compose.yml VSI &>/dev/null
}

case $1 in
  start|stop|restart|update) "$1" ;;
esac