#!/bin/bash
### BEGIN INIT INFO
# Provides:          loginvsid
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: loginvsid
# Description:       loginvsid
### END INIT INFO

start() {
  cd /loginvsi
  export $(cat .env); docker stack deploy --compose-file ./docker-compose.yml VSI
  sleep 5
  TOTAL=docker stack services VSI --format "{{.Replicas}}" | wc -l
  MAXCOUNT = 600
  COUNT = 0
  while [ $COUNT -le $MAXCOUNT ]
  do
    sleep 1
    $COUNT = $COUNT + 1
    RUNNING=docker stack services VSI --format "{{.Replicas}}" | grep "1/1" | wc -l
    if [ $TOTAL -eq $RUNNING ] then
      echo "All services up and running..."
      break
    else
      echo "Not all services up and running, attempt $COUNT of $MAXCOUNT"
    fi  
  done

}

stop() {
  echo "Nothing to stop, yet"   
}

case $1 in
  start|stop) "$1" ;;
esac