#!/bin/bash
TITLE=$(cat /loginvsi/.title)
# add first_run script
netadapters=$(ip -o link show | while read -r num dev fam mtulabel mtusize qlabel queu statelabel state modelabel mode grouplabel group qlenlabel qlen maclabel mac brdlabel brcast; do 
        if [[ ${mac} != brd && ${mac} != 00:00:00:00:00:00 && ${dev} != br-*  && ${dev} != veth* ]]; then
            echo ${dev%/*}; 
        fi     
    done
    )
netadapter=$(echo $netadapters | tail -1 | awk '{split($1,n,":");print n[1]}')
ip=$(ip -o addr show $netadapter primary scope global | while read -r num dev fam addr rest; do 
        if [[ ${dev} != docker* ]]; then
            echo ${addr%/*}; 
        fi       
    done
    )
gateway=$(ip -o route list | grep default | while read -r default via gateway dev net; do echo $gateway;done )
netmask=$(ifconfig $netadapter | grep netmask | cut -d" " -f13)
nameserversarray=$(cat /etc/resolv.conf | grep -i nameserver|head -n2|cut -d ' ' -f2)
nameservers=$(echo $(echo "${nameserversarray[@]}"))
broadcast=$(ip a s dev $netadapter | awk '/inet / {print $4}')
dnssuffix=$(grep search /etc/resolv.conf | while read -r search suffix; do echo $suffix;done )
if [ ! -f "/loginvsi/first_run.chk" ]; then
trap 'echo "You cannot cancel this script"' SIGINT
    # check for interactive shell
    if ! grep -q "noninteractive" /proc/cmdline ; then
        stty sane

        # ask questions
        echo "Welcome to $TITLE"
        echo "Please help answer the following questions to get the system setup..."
        
        read -ep " Please enter your preferred hostname ($(hostname)):" new_hostname        
        read -ep " Please enter your preferred domain ($(domainname)):" new_domain        
        read -ep " Please choose a network configuration mode dhcp or static (D/s) " network
        case $network in
            s|S)
                
                echo "Configuring network using static address..."
                read -ep " Please provide the new ip address ($ip): " new_ip
                read -ep " Please provide the netmask ($netmask): " new_netmask
                read -ep " Please provide the default gateway ($gateway): " new_gateway
                read -ep " Please provide the nameservers ($nameservers) " new_nameservers
                read -ep " Please provide the dns search suffix ($new_domain) " new_dnssuffix
                

                [[ -z "$new_dnssuffix" ]] && new_dnssuffix=$new_domain
                [[ ! -z "$new_ip" ]] && ip=$new_ip                                
                [[ ! -z "$new_netmask" ]] && netmask=$new_netmask
                [[ ! -z "$new_gateway" ]] && gateway=$new_gateway
                [[ ! -z "$new_nameservers" ]] && nameservers=$new_nameservers
                
                [[ ! -z "$new_dnssuffix" ]] && dnssuffix=$new_dnssuffix
                
                
                
                echo "
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto $netadapter
iface $netadapter inet static        
    address $ip
    netmask $netmask
    gateway $gateway
    dns-search $dnssuffix
    dns-nameservers $nameservers
                " > /etc/network/interfaces
                ;;
            *)
                echo "Configuring network using dhcp..."
               echo "
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto $netadapter
iface $netadapter inet dhcp        
    " > /etc/network/interfaces
      ;;
        esac

        while :       
        do        
            read -ersp " Please enter a new password for admin: " password
            read -ersp " Please confirm the new password: " password2
            if [ $password != $password2 ]; then
                echo "Passwords do not match, try again..."
            else
                echo "admin:$password" | chpasswd
                echo "Password updated successfully"
                break
            fi
        done
    fi

   
    # set fqdn
     [[ -z $new_hostname ]] && new_hostname=$(hostname)
     [[ -z $new_domain ]] && new_domain="local"
    export fqdn="$new_hostname.$new_domain"    
    echo " Setting fqdn: $fqdn"
	
    
    echo " Setting hostname: $new_hostname"
    # update hostname
    echo "$new_hostname" > /etc/hostname
    echo "kernel.domainname=$new_domain" >>/etc/sysctl.conf
    sed -i "s@loginvsi-ng.loginvsi-ng@$fqdn@g" /etc/hosts
    sed -i "s@loginvsi-ng@$new_hostname@g" /etc/hosts
    
    hostname "$new_hostname"
	
	echo "   
    Welcome to $TITLE
    $TITLE appliance is not yet configured!
    Logon with admin and the password you set previously
	"  > /etc/issue
    
	
	adminpass=$(docker run --rm httpd:2.4-alpine htpasswd -nbB admin ${password} | cut -d ":" -f 2)
	sed -i "s,{{ADMIN_PASS}},${adminpass},g" /usr/bin/loginvsid
	
	touch -f /loginvsi/first_run.chk
	
	echo "#!/bin/bash" > /home/admin/.bash_profile
	echo "if [ ! -f '/loginvsi/second_run.chk' ]; then"  >> /home/admin/.bash_profile
	echo "  echo ${password} | sudo -S -p '' echo 'Starting LoginVSI configuration tool...'" >> /home/admin/.bash_profile
	echo "  sudo /loginvsi/firstrun" >> /home/admin/.bash_profile
	echo "fi" >> /home/admin/.bash_profile
	chmod +x /home/admin/.bash_profile
    echo $password >/root/.password
	
	reboot  
	trap SIGINT	
fi 
if [ ! -f "/loginvsi/second_run.chk" ]; then
	trap 'echo "You cannot cancel this script"' SIGINT
	echo "Resetting SSH keys..."
    rm /etc/ssh/ssh_host_*
    dpkg-reconfigure openssh-server &>/dev/null
    /etc/init.d/ssh restart &>/dev/null
    echo "Generating self-signed certificates..."
	export fqdn=$(hostname).$(domainname)
	mkdir /certificates
	cert_password=$(openssl rand -hex 32)    
	#Docker (encrypted key)
    /loginvsi/bin/sslgen -c=NL -s=Noord-Holland -l=Amsterdam -o="Login VSI B.V." -u=Development -n=${fqdn} -e=info@loginvsi.com -d=999999 -w=$cert_password -p=/certificates/
	   

    echo "SSL_CERTIFICATE_KEY_PATH=/certificates/${fqdn}.key" >/loginvsi/.env
    echo "SSL_CERTIFICATE_PATH=/certificates/${fqdn}.crt" >>/loginvsi/.env
    echo "GATEWAY_PORT=443" >>/loginvsi/.env

    
    echo "Initting docker swarm..."  
    docker swarm init &>/dev/null
    echo $(cat /root/.password) | docker secret create ADMIN_PASSWORD - &>/dev/null
    echo $(cat /root/.password) | docker secret create USER_PASSWORD - &>/dev/null
    rm /root/.password
    echo $cert_password | docker secret create VSI_SSL_CERTIFICATE_KEY_PASSWORD - &>/dev/null
    echo $cert_password | docker secret create APPLIANCEMANAGEMENT_PFX_PASSWORD - &>/dev/null
    echo $(cat /certificates/${fqdn}.pfx) | docker secret create APPLIANCEMANAGEMENT_PFX - &>/dev/null
    
    # create data volume folders for the dbs
    mkdir /loginvsi/data
    echo "DB_ROOT=/loginvsi/data" >>/loginvsi/.env
    for f in $(cat /loginvsi/docker-compose.yml | grep "{DB_ROOT}")
    do 
        folder=$(echo $f | cut -d"-" -f2 | cut -d"/" -f2 | cut -d":" -f1) 
        if [ ! -z $folder ]; then
          if [ ! -d /loginvsi/data/$folder ]; then        
              mkdir /loginvsi/data/$folder; 
          fi
        fi
    done

    chmod +x /usr/bin/loginvsid
    chown root:root /usr/bin/loginvsid
	
    
    
    #echo "HOST_URL=https://${fqdn}" >>/loginvsi/.env

    #sed -i s,GATEWAY_PORT=3000,GATEWAY_PORT=443, /loginvsi/.env
    #sed -i s,HOST_URL=https://localhost.loginvsi.com:3000,HOST_URL=https://${fqdn},  /loginvsi/.env
    #sed -i s,SSL_CERTIFICATE_KEY_PATH=..\\..\\..\\Certificates\\certificate.key,SSL_CERTIFICATE_KEY_PATH=/certifcates/certificate.key, /loginvsi/.env
    #sed -i s,SSL_CERTIFICATE_PATH=..\..\..\Certificates\certificate.crt,SSL_CERTIFICATE_PATH=/certifcates/certificate.crt, /loginvsi/.env
    systemctl enable loginvsid &>/dev/null
    touch -f /loginvsi/second_run.chk
	
    passwd -dl root &>/dev/null
    head -n -2 /etc/issue > /etc/issue.tmp; mv /etc/issue.tmp /etc/issue
    
    echo "   
    Welcome to $TITLE
    $TITLE appliance is configured!
    Main interface https://\4{$netadapter} or https://\n.\o
    Admin interface: https://\4{$netadapter}:9000 or https://\n.\o:9000
    "  > /etc/issue    

    echo "#!/bin/bash
    sudo pdmenu -c -q /loginvsi/menu/pdmenurc" > /usr/bin/startmenu
    chmod +x /usr/bin/startmenu
    echo "admin ALL = (root) NOPASSWD: /usr/bin/pdmenu" >>/etc/sudoers
    sed -i 's#admin:x:1000:1000:administrator,,,:/home/admin:/bin/bash#admin:x:1000:1000:administrator,,,:/home/admin:/usr/bin/startmenu#' /etc/passwd
    echo "/usr/bin//startmenu" >> /etc/shells
	
	
	#cleanup
	echo "Cleaning up..."
	# Cleanup
    rm -rf /home/admin/*
    rm -rf /home/admin/.bash_history
    rm -rf /root/.bash_history
    rm -rf /root/.ssh

	
trap SIGINT

reboot    
   
fi