#!/bin/bash
while :       
    do        
        read -ersp " Please enter a new password for admin: " password
        read -ersp " Please confirm the new password: " password2
        if [ $password != $password2 ]; then
            echo "Passwords do not match, try again..."
        else
            echo "admin:$password" | chpasswd
            adminpass=$(docker run --rm httpd:2.4-alpine htpasswd -nbB admin ${password} | cut -d ":" -f 2)
            currentpass=$(cat /usr/bin/loginvsid | grep "ADMINPASS=" | cut -d':' -f2 | cut -d"'" -f2)
            sed -i s,$currentpass,$adminpass, /usr/bin/loginvsid
            echo "Password updated successfully"
            break
        fi
    done



	