#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

    
netadapter=$1
dhcp=$2
ip=$3
netmask=$4
gateway=$5
nameservers="$6"
search="$7"

echo "Setting $netadapter with mode $dhcp $ip $netmask $gateway $nameservers $search"
if [[ $dhcp == "dhcp" ]]; then
  
  cp /etc/network/interfaces /etc/network/interfaces.bck
  awk -f /loginvsi/menu/changeInterface.awk /etc/network/interfaces device=${netadapter} mode=dhcp action=remove >/etc/network/interfaces2;
  rm /etc/network/interfaces; mv /etc/network/interfaces2 /etc/network/interfaces;
  awk -f /loginvsi/menu/changeInterface.awk /etc/network/interfaces device=${netadapter} mode=dhcp action=add >/etc/network/interfaces2;
  rm /etc/network/interfaces;mv /etc/network/interfaces2 /etc/network/interfaces
else
  cp /etc/network/interfaces /etc/network/interfaces.bck
  awk -f /loginvsi/menu/changeInterface.awk /etc/network/interfaces device=${netadapter} mode=static action=remove >/etc/network/interfaces2;
  rm /etc/network/interfaces;mv /etc/network/interfaces2 /etc/network/interfaces;
  awk -f /loginvsi/menu/changeInterface.awk /etc/network/interfaces device=${netadapter} mode=static action=add address=${ip} netmask=${netmask} "dns=${nameservers}" "dnssearch=${search}" gateway=${gateway} >/etc/network/interfaces2;
  rm /etc/network/interfaces;mv /etc/network/interfaces2 /etc/network/interfaces;
  sed -i 's,dnssearch,dns-search,g' /etc/network/interfaces
  tac /etc/network/interfaces | sed '1,/gateway/{s/gateway/#gateway/}' | tac >/etc/network/interfaces2
  rm /etc/network/interfaces;mv /etc/network/interfaces2 /etc/network/interfaces;
fi
cat /etc/network/interfaces
echo "Done, restarting network interface $netadapter"
ifdown $netadapter
ifup --ignore-errors $netadapter