#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
#new_hostname=`echo $1 | awk -F. '{ print $1 }'`
#new_domain=`echo $1 |awk -F. '{$1="";OFS="." ; print $0}' | sed 's/^.//' `
new_hostname=`echo "$1" | cut -f1 -d.`
new_domain=`expr "$1" | cut -f2- -d.`
current_hostname=$(hostname)
current_domainname=$(domainname)
export fqdn="$new_hostname.$new_domain"    
echo " Setting fqdn: $fqdn"
echo " Setting domainname:" $new_domain
echo " Setting hostname: $new_hostname"
# update hostname
echo "$new_hostname" > /etc/hostname
echo "kernel.domainname=$new_domain" >>/etc/sysctl.conf
sed -i "s@$current_hostname.$current_domainname@$fqdn@g" /etc/hosts
sed -i "s@$current_hostname@$new_hostname@g" /etc/hosts

hostname "$new_hostname"
domainname "$new_domain"